--Activity 4:  Implementing Data Retrieval Operations

--On SQL Console Create a Select Statement that will display all Resources Name under SAP Hana and SAP UI5 Skill where DELETEFLAG is not 1.
SELECT t1.FIRSTNAME, t1.LASTNAME, t3.SKILLNAME
FROM "11435202_1"."HANA_TRAINING.data::TB_EMLOYEE" t1
JOIN "11435202_1"."HANA_TRAINING.data::TB_SKILLSET" t2
ON t1.SAPNO = t2.SAPNO
JOIN "11435202_1"."HANA_TRAINING.data::TB_SKILL_INFO" t3
ON t2.SKILLID = t3.SKILLID
WHERE t3.SKILLNAME IN ('SAP HANA', 'SAP UI5')
  AND t1.DELETEFLAG != 1
  AND t2.DELETEFLAG != 1;

--On SQL Console Create a select statement that will display the following columns using INNER JOIN
/* a. SAPNO
b. FIRSTNAME and LASTNAME as EMPLOYEENAME
c. SKILLNAME
d. MANAGERSAPNO
e. PROJECTNAME
f. DELETEFLAG is 0. */

SELECT 
    t1.SAPNO, 
    t1.FIRSTNAME || ' ' ||  t1.LASTNAME AS EMPLOYEENAME, 
    t3.SKILLNAME, 
    t4.MANAGERSAPNO, 
    t5.PROJECTNAME
FROM 
    "11435202_1"."HANA_TRAINING.data::TB_EMLOYEE" t1
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_SKILLSET" t2
    ON t1.SAPNO = t2.SAPNO
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_SKILL_INFO" t3
	ON t2.SKILLID = t3.SKILLID
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECT" t4
	ON t2.SAPNO = t4.SAPNO AND t2.SKILLID = t4.SKILLID
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECTID_INFO" t5
	ON t4.PROJECTID = t5.PROJECTID
WHERE 
    t1.DELETEFLAG = 0 
    AND t2.DELETEFLAG = 0 
    AND t4.DELETEFLAG = 0;

-- On SQL Console Create a select statement that will display total count of each Resources group by manager.
SELECT 
    t1.MANAGERSAPNO, 
    t2.FIRSTNAME || ' ' ||  t2.LASTNAME AS MANAGERNAME, 
    COUNT(DISTINCT t1.SAPNO) AS TOTAL_RESOURCES
FROM 
    "11435202_1"."HANA_TRAINING.data::TB_PROJECT" t1
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_MANAGER" t2
    ON t1.MANAGERSAPNO = t2.SAPNO
WHERE 
    t1.DELETEFLAG = 0
GROUP BY 
    t1.MANAGERSAPNO, 
    t2.FIRSTNAME, 
    t2.LASTNAME;

--On SQL Console Create a select statement that will display SAPNO, EMPLOYEENAME, PROJECTNAME of those Resources the skill name SAP HANA.
SELECT 
    t4.SAPNO, 
    t4.FIRSTNAME || ' ' ||  t4.LASTNAME AS EMPLOYEENAME, 
    t5.PROJECTNAME
FROM "11435202_1"."HANA_TRAINING.data::TB_SKILLSET" t1
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_SKILL_INFO" t2
	ON t1.SKILLID = t2.SKILLID
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECT" t3
	ON t1.SAPNO = t3.SAPNO AND t2.SKILLID = t3.SKILLID
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_EMLOYEE" t4
	ON t1.SAPNO = t4.SAPNO
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECTID_INFO" t5
	ON t3.PROJECTID = t5.PROJECTID
WHERE 
    t2.SKILLNAME = 'SAP HANA' 
    AND t1.DELETEFLAG = 0
    AND t3.DELETEFLAG = 0;

--On SQL Console Create a select statement that will display SAPNO, EMPLOYEENAME, PROJECTNAME and MANAGERNAME (FIRSTNAME and LASTNAME) whose hire date from December 2013 to August 2014
SELECT 
    t1.SAPNO, 
    t1.FIRSTNAME || ' ' ||  t1.LASTNAME AS EMPLOYEENAME,
    t3.PROJECTNAME, 
    t4.FIRSTNAME || ' ' ||  t4.LASTNAME AS MANAGERNAME
FROM 
    "11435202_1"."HANA_TRAINING.data::TB_EMLOYEE" t1
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECT" t2
	ON t1.SAPNO = t2.SAPNO
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_PROJECTID_INFO" t3
	ON t2.PROJECTID = t3.PROJECTID
INNER JOIN "11435202_1"."HANA_TRAINING.data::TB_MANAGER" t4
	ON t2.MANAGERSAPNO = t4.SAPNO
WHERE 
    t1.HIREDATE BETWEEN '2013-12-01' AND '2014-08-31'
    AND t1.DELETEFLAG = 0
    AND t2.DELETEFLAG = 0;