-- Activity 5: Test Stored Procedure

-- Testing SP_CREATE_EMPLOYEE
CREATE LOCAL TEMPORARY TABLE #Emp (
  	SAPNO INTEGER ,
	EMPEID NVARCHAR(50),
	FIRSTNAME NVARCHAR(100),
	LASTNAME NVARCHAR(100),
	BIRTHDATE DATE,
	AGE INTEGER,
	HIREDATE DATE,
	DELETEFLAG NVARCHAR(1)
);

INSERT INTO #Emp (SAPNO,EMPEID,FIRSTNAME, LASTNAME, BIRTHDATE, AGE, HIREDATE, DELETEFLAG )
VALUES(
	1/*SAPNO <INTEGER>*/,
	'joy.m.jacusalem'/*EMPEID <NVARCHAR(50)>*/,
	'Joy'/*FIRSTNAME <NVARCHAR(100)>*/,
	'Jacusalem'/*LASTNAME <NVARCHAR(100)>*/,
	'1996-03-17'/*BIRTHDATE <DATE>*/,
	29/*AGE <INTEGER>*/,
	'2017-07-17'/*HIREDATE <DATE>*/,
	''/*DELETEFLAG <NVARCHAR(1)>*/
);

CALL "11435202_1"."HANA_TRAINING.procedures::SP_CREATE_EMPLOYEE"(IP_ROW => #Emp/*<TABLE_TYPE>*/,OP_MESSAGE => ?);

COMMIT;

-- Testing SP_UPDATE_EMPLOYEE

CREATE LOCAL TEMPORARY TABLE #EmpUpdate1 (
  	SAPNO INTEGER ,
   EMPEID NVARCHAR(50),
   FIRSTNAME NVARCHAR(100),
   LASTNAME NVARCHAR(100),
   BIRTHDATE DATE,
   AGE INTEGER,
   HIREDATE DATE,
   DELETEFLAG NVARCHAR(1)
);

INSERT INTO #EmpUpdate1 (SAPNO, EMPEID,FIRSTNAME,LASTNAME,BIRTHDATE,AGE,HIREDATE, DELETEFLAG )
VALUES(
	1/*SAPNO <INTEGER>*/,
	'joy.m.jacusalem'/*EMPEID <NVARCHAR(50)>*/,
	'Joy'/*FIRSTNAME <NVARCHAR(100)>*/,
	'Jacusalem'/*LASTNAME <NVARCHAR(100)>*/,
	'1996-03-17'/*BIRTHDATE <DATE>*/,
	21/*AGE <INTEGER>*/,
	'2017-07-17'/*HIREDATE <DATE>*/,
	'0'/*DELETEFLAG <NVARCHAR(1)>*/
);

CALL "11435202_1"."HANA_TRAINING.procedures::SP_UPDATE_EMPLOYEE"(IP_ROW => #EmpUpdate1/*<TABLE_TYPE>*/,OP_MESSAGE => ?);
COMMIT;

-- -- Testing SP_DELETE_EMPLOYEE

CREATE LOCAL TEMPORARY TABLE #EmpDelete (
  	SAPNO INTEGER 
);

INSERT INTO #EmpDelete (SAPNO)
VALUES(
	1/*SAPNO <INTEGER>*/
);
CALL "11435202_1"."HANA_TRAINING.procedures::SP_DELETE_EMPLOYEE"(IP_ROW => #EmpDelete/*<TABLE_TYPE>*/,OP_MESSAGE => ?);
COMMIT;

-- TESTING SP_READ_EMPLOYEE

CALL "11435202_1"."HANA_TRAINING.procedures::SP_READ_EMPLOYEE"(IP_SAPNO => 10001/*<INTEGER>*/,OP_TABLE => ?);

---- TB_SKILLSET
-- Testing SP_CREATE_SKILLSET

CREATE LOCAL TEMPORARY TABLE #SkillSet (
   SAPNO INTEGER ,
   SKILLID INTEGER,
   PROFLEVEL NVARCHAR(2),
   DATESTART NVARCHAR(500),
   DATEEND NVARCHAR(500),
   DELETEFLAG NVARCHAR(1)
);

INSERT INTO #SkillSet ( SAPNO, SKILLID, PROFLEVEL, DATESTART, DATEEND,DELETEFLAG)
VALUES(
	1/*SAPNO <INTEGER>*/,
	1/*SKILLID <INTEGER>*/,
	'P5'/*PROFLEVEL <NVARCHAR(2)>*/,
	'1992-07-13'/*DATESTART <NVARCHAR(500)>*/,
	'9999-01-01'/*DATEEND <NVARCHAR(500)>*/,
	'0'/*DELETEFLAG <NVARCHAR(1)>*/
);

CALL "11435202_1"."HANA_TRAINING.procedures::SP_CREATE_SKILLSET"(IP_ROW => #SkillSet/*<TABLE_TYPE>*/,OP_MESSAGE => ?);

COMMIT;


-- Testing SP_UPDATE_SKILLSET

CREATE LOCAL TEMPORARY TABLE #SkillSetUp (
   SAPNO INTEGER ,
   SKILLID INTEGER,
   PROFLEVEL NVARCHAR(2),
   DATESTART NVARCHAR(500),
   DATEEND NVARCHAR(500),
   DELETEFLAG NVARCHAR(1)
);

INSERT INTO #SkillSetUp ( SAPNO, SKILLID, PROFLEVEL, DATESTART, DATEEND,DELETEFLAG)
VALUES(
	1/*SAPNO <INTEGER>*/,
	1/*SKILLID <INTEGER>*/,
	'P4'/*PROFLEVEL <NVARCHAR(2)>*/,
	'1992-07-13'/*DATESTART <NVARCHAR(500)>*/,
	'9999-01-01'/*DATEEND <NVARCHAR(500)>*/,
	'0'/*DELETEFLAG <NVARCHAR(1)>*/
);

CALL "11435202_1"."HANA_TRAINING.procedures::SP_UPDATE_SKILLSET"(IP_ROW => #SkillSetUp/*<TABLE_TYPE>*/,OP_MESSAGE => ?);

COMMIT;

- -- Testing SP_DELETE_SKILLSET

CREATE LOCAL TEMPORARY TABLE #SkillDel (
  	SAPNO INTEGER 
);

INSERT INTO #SkillDel (SAPNO)
VALUES(
	1/*SAPNO <INTEGER>*/
);
CALL "11435202_1"."HANA_TRAINING.procedures::SP_DELETE_SKILLSET"(IP_ROW => #SkillDel/*<TABLE_TYPE>*/,OP_MESSAGE => ?);
COMMIT;

-- TESTING SP_READ_SKILLSET

CALL "11435202_1"."HANA_TRAINING.procedures::SP_READ_SKILLSET"(IP_SAPNO => 10001/*<INTEGER>*/,OP_TABLE => ?);
